jdbc:
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://localhost:1433;databaseName=Repairs
  username: sa
  password: pass-word1
 
hibernate:
  dialect: org.hibernate.dialect.SQLServerDialect
  connection:
    driver_class: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: pass-word1
    url: jdbc:sqlserver://localhost:1433;databaseName=Repairs