jdbc:
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://STEVE-PC:1433;databaseName=Repairs
  username: rapidoid
  password: password
 
hibernate:
  dialect: org.hibernate.dialect.SQLServerDialect
  connection:
    driver_class: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: rapidoid
    password: password
    url: jdbc:sqlserver://STEVE-PC:1433;databaseName=Repairs