on:
  port: 8000
  address: 0.0.0.0
 
admin:
  port: same
  address: 0.0.0.0
 
app:
  domain: ''
  brand: App
  search: false
  navbar: true
  fluid: false
  cdn: auto # in DEV mode is false, in PRODUCTION is true
  contextPath: /
  home: /
  menu: {}
 
users:
  root:
    roles:
      - administrator
      - owner
    password: root # PLEASE change this
