jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306?useSSL=false
  username: rapidoid
  password: C04JCzJXKfkLWwYD
  useSSL: false
 
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  connection:
    driver_class: com.mysql.jdbc.Driver
    username: rapidoid
    password: C04JCzJXKfkLWwYD
    url: jdbc:mysql://localhost:3306?useSSL=false
